@startuml

title Pivot project architecture

package "Pivot library" {
  folder "ECS library" as ecs {
  
    component Scene as scene {
      [Entity] as entity
      [Component] as component
      [System] as system
      [Event] as event
      
      event --> system: triggers
      event <.. system: listen to
      event ..> entity: applies on 0 or more
      system --> component: updates
      component .> entity: stores data of
    }
  }
  
  component [Graphics library] as graphics
  component [Scripting engine] as scripting
  component [Pivot Engine] as pivot
  
  pivot --> scene: creates and runs
  pivot -> graphics: uses to render the game
  pivot --> scripting: uses
  
}
component [Game Launcher] as launcher
launcher --> pivot: starts

component [Editor] as editor
editor --> pivot: starts

folder "Saved game" {
  node "Pivot script file" as script_file
  node "Scene file" as scene_file
}

script_file ..> component: contains definition
script_file ..> system: contains definition
scene_file ..> scene: contains data
scene_file ..> script_file: depends on

pivot --> scene_file: loads and saves
scripting --> script_file: loads

@enduml
